### PR TITLE
style: Corrected z-index from user dropdown menu

### LINKED ISSUE #220: Design: Icon overlaps in mobile view
B55B2723-D231-4AA4-B064-DF9F98DF9D0C_4_5005_c

in mobile view pizza icon overlaps the user dropdown menu

_Originally posted by @KrisMannino in https://github.com/open-sauced/hot/issues/216#issuecomment-1192670375_

### PR DESCRIPTION
**Pull request by NsdHSO**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #220

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@KrisMannino take a look at this.

**Comment by 0-vortex** [comment]
image

**Comment by KrisMannino** [comment]
1A6FA1A9-249A-402D-9C1D-BA30B1C2DBD8_4_5005_c
Screenshot_20220725-181639_Firefox

works on Android-Mozilla and OSX-Mozilla/Chrome

**Review by bdougie — APPROVED** [review]
LGTM

**Pull request merged**
