### PR TITLE
feat: add Loading skeleton in Hero

### PR DESCRIPTION
**Pull request by SunGoldTech**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR adds loading skeleton to the hero section

## Related Tickets & Documents
Feature #297

## Mobile & Desktop Screenshots/Recordings
Desktop

Screenshot (25)

Mobile

Screenshot (30)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Seeing this live, I am not convinced this is need or the correct solution. 

Showing the skeleton on each load is more of a nuance. The 200 mili seconds is due the de ounce and intended

**Comment by SunGoldTech** [comment]
> Seeing this live, I am not convinced this is need or the correct solution.
> 
> Showing the skeleton on each load is more of a nuance. The 200 mili seconds is due the de ounce and intended
> 
> This issue needs more discussion @open-sauced/triage team.

Had same thoughts in mind about this solution... but still havent figured out what will best suite this case. I would suggest closing  this issue till a better alternative is available.. just a suggestion though :)

**Comment by 0-vortex** [comment]
> > Seeing this live, I am not convinced this is need or the correct solution.
> 
> > 
> 
> > Showing the skeleton on each load is more of a nuance. The 200 mili seconds is due the de ounce and intended
> 
> > 
> 
> > This issue needs more discussion @open-sauced/triage team.
> 
> 
> 
> Had same thoughts in mind about this solution... but still havent figured out what will best suite this case. I would suggest closing  this issue till a better alternative is available.. just a suggestion though :)

I don't think this is bad actually. We are getting current results from supabase postgrest, switchning to the global backed api could increase the loading timer above 200ms, then there is the debounce, which 200ms is not enough, I would argue half a second is decent in terms of supporting mobile users who type at a rate of 300+. Increasing those values results in a smoother experience and then displaying 1 loader (more like a spinner tbh) could make things feel like home.

I do agree having 3 skeletons for potentially less than 3 results invalidates the requirement for content skeletons and the web 1.0 default for that is circular loading animations 😅

**Comment by 0-vortex** [comment]
whatever ends up happening, kudos for the amazing effort! 🍕

**Comment by bdougie** [comment]
> I do agree having 3 skeletons for potentially less than 3 results invalidates the requirement for content skeletons and the web 1.0 default for that is circular loading animations 😅

Circular or loading animations seems like a better approach. Can link to what other solutions are out there?

**Comment by SunGoldTech** [comment]
> > I do agree having 3 skeletons for potentially less than 3 results invalidates the requirement for content skeletons and the web 1.0 default for that is circular loading animations sweat_smile
> 
> Circular or loading animations seems like a better approach. Can link to what other solutions are out there?

Cool.. can I replace the skeleton with a spinner instead?

**Comment by SunGoldTech** [comment]
Or rather,  a beat loader like this 👇

**Comment by NsdHSO** [comment]
Indeed for our implementation it is a good approach to have circular. I suggest this lib, open to discussion [react-loading](https://www.npmjs.com/package/react-loading), to avoid reinventing the wheel.

**Review by NsdHSO — COMMENTED** [review]
Good job, Please can you just put your changes, to make it easier to review your PR. I suggest that when you open a new PR you should be the first to review

**Comment by bdougie** [comment]
Let's move the conversation back to the issue.

**Comment by 0-vortex** [comment]
> Indeed for our implementation it is a good approach to have circular. I suggest this lib, open to discussion [react-loading](https://www.npmjs.com/package/react-loading), to avoid reinventing the wheel.

That library is not maintained and breaking in React 18, just a heads up.

**Pull request closed without merging**
