### PR TITLE
chore: Bump *almost* all packages ⚡

### PR DESCRIPTION
**Pull request by Pranav-yadav**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR bumps the *almost* all packages. 

## Related Tickets & Documents

NA

## Mobile & Desktop Screenshots/Recordings

NA

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed (_I guess_)

## [optional] Are there any post-deployment tasks we need to perform?

- check if build is green

## [optional] What gif best describes this PR or how it makes you feel?

IWantRegularUpdatesUpdateMeGIF

### CODE REVIEW

**Comment by 0-vortex** [comment]
Hello and thank you for a brave first contribution, making changes to the npm lock file is always an adventure. There are some potential blockers you might encounter in shipping this:
1. this PR is using `lockfileVesion=2` while `.npmrc` enforces version 3
1. `npm shrinkwrap` is needed for predictability, this PR is removing it right now
1. the `typescript` major upgrade has known breaking changes that would have to be addressed, adding technical debt to this PR

Would be very happy to pass this if it deals with `1` and `2` and would only upgrade non-major versions. For that purpose would use something like https://www.npmjs.com/package/npm-check-updates in interactive mode, going one step at a time or without any majors 🍕

**Comment by Pranav-yadav** [comment]
Hey @0-vortex 👋 

Thanks for initial review.

I'm kind of having difficulty w/ `npm ci` as well as `npm install`. Below is the error:

<details>

image
</details>

WDYT what might be the reason? Or am I missing something?

**Comment by 0-vortex** [comment]
> Hey @0-vortex 👋
> 
> Thanks for initial review.
> 
> I'm kind of having difficulty w/ `npm ci` as well as `npm install`. Below is the error:
> 
> WDYT what might be the reason? Or am I missing something?

The squuosh cli is unmaintained for a while and only supports v16 of nodejs, that's one reason I forgot to mention in the above list :<

Would not go into upgrading packages as the project is in maintenance mode right now, unlike https://github.com/open-sauced/insights which is accepting papercuts! 🍕

**Comment by Pranav-yadav** [comment]
>as the project is in maintenance mode right now.

Ohhh.
I guess we should mention this in the top section of the README...

Thanks.

PS: Then how does the CI still passes on github (not this one, but generally..)? the npm ci/install run specifically... Just being curious. 🤔

**Comment by Pranav-yadav** [comment]
Closing this, as the Project is in **Maintenance Mode**.
Note for Maintainers - do ping me in case these changes are required 👍

**Comment by 0-vortex** [comment]
> >as the project is in maintenance mode right now.
> 
> 
> 
> Ohhh.
> 
> I guess we should mention this in the top section of the README...
> 
> 
> 
> Thanks.
> 
> 
> 
> PS: Then how does the CI still passes on github (not this one, but generally..)? the npm ci/install run specifically... Just being curious. 🤔 

They are still running with node16, dodging the message :D

**Pull request closed without merging**
