### PR TITLE
fix: Popular text not aligned

### PR DESCRIPTION
**Pull request by Ryankolsen**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Before:
image

After (fixed 
image

## Added tests?

- [ ] 👍 yes
- [ x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Nope

## [optional] What gif best describes this PR or how it makes you feel?

lego-batman

### CODE REVIEW

**Comment by Ryankolsen** [comment]
I have no idea how to change my commit message after I pushed it....I also think you fixed this for me. Am I good to go?

**Comment by bdougie** [comment]
Creates adverse affect on mobile. Perhaps keep mobile center with a small screen prefix

image

**Comment by bdougie** [comment]
The more I look at the mobile left aligned, the more I don't mind

**Comment by bdougie** [comment]
>I have no idea how to change my commit message after I pushed it....I also think you fixed this for me. Am I good to go?

The complaint was the PR title, but FWIW `git commit --amend` or rebase locally to change commit titles

**Comment by shamimbinnur** [comment]
We don't have any design for the Nav. Any suggestion for that? @bdougie

**Comment by shamimbinnur** [comment]
I have used the existing function for the voting system. Confused, does that work? @0-vortex

**Comment by Ryankolsen** [comment]
Ahhh, I see. Sometimes it helps when I remember to read, thank you!!! Sorry, I did try git commit --ammend, but clearly that wasn't my problem!

**Comment by 0-vortex** [comment]
> Ahhh, I see. Sometimes it helps when I remember to read, thank you!!! Sorry, I did try git commit --ammend, but clearly that wasn't my problem!

We squash the commits from a pull request into a commit with the name of the pull request, you don't ever need to send ammends or force pushes, and updating the pull request does the trick on your end, while maintainers have the ability to also rewrite the message in the merge dialog (that is, pushing a non-compliant PR title and make it compliant with the merge dialog edit)! 🍕

**Pull request merged**
