### PR TITLE
fix: popular text is now aligned

### PR DESCRIPTION
**Pull request by AlexBurneikis**
#253 fixed, refer to my comment on the issue for how this works :)

### CODE REVIEW

**Comment by bdougie** [comment]
Welcome to the party. We did get a contribution for this already on #246. That pr and this one both leave out consideration for mobile 

image

**Comment by AlexBurneikis** [comment]
Aha, my bad, I'll have a quick looksie

**Comment by AlexBurneikis** [comment]
Should work now, I've changed it back to use space-y-2 and sm:space-y-0 so that it works for mobile and doesn't apply it on desktop

**Comment by bdougie** [comment]
Thanks for the work on this, however I went with #253. That result visually is the same and that contributor followed the contributing guidelines. Feel free to take another issue.

Again appreciate the work, but do consider assigning yourself to the issue before beginning work in the future.

**Pull request closed without merging**
