### PR TITLE
fix: unwanted drop shadow to the right side of the hero section.

### LINKED ISSUE #227: Bug: incorrect gradient tearing based on screen size
### Describe the bug

The gradient is loaded as a sized svg image but not scaled properly and it includes the drop shadow as well, depending on platform and screen size this can lead to tearing or inconsistent UI.

Ways to improve this:
- scale the [public/gradBG.svg](https://github.com/open-sauced/hot/blob/beta/public/gradBG.svg) background correctly into multiple css properties
- replace with css gradient

### Steps to reproduce

1. Go to https://beta.hot.opensauced.pizza
2. Apply some wide dimensions or weird screen
3. Click "Sign In"
4. Get a hard to debug drop shadow: 

Screenshot 2022-07-23 at 01 21 19

### Affected services

hot.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

introduced in #210

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Basically, the SVG file of the hero's background had an issue that resulted in the unwanted drop shadow to the right side of the hero section. So, I have slightly tweaked the SVG file which has fixed the problem.

## Related Tickets & Documents
Fixes #227 

## Mobile & Desktop Screenshots/Recordings

Before:
Screenshot 2022-12-02 at 9 25 07 PM

After:
Screenshot 2022-12-02 at 9 25 16 PM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — CHANGES_REQUESTED** [review]
LGTM, but can you also remove it from the left side? 🍕

**Comment by shamimbinnur** [comment]
> https://deploy-preview-402--hot-sauced-ui.netlify.app/

I can see there is an inner shadow on the left side which seems to be intentional by the designer. Can we keep it? @0-vortex

**Comment by bdougie** [comment]
@shamimbinnur I don't see the difference between the before and after. I honestly was not bothered by this and was confused because the linked issue seems unrelated. https://github.com/open-sauced/hot/issues/227

My recommendation is to annotate the screenshot. Also provide more context on how this relates to the issue.

**Comment by 0-vortex** [comment]
> @shamimbinnur I don't see the difference between the before and after. I honestly was not bothered by this and was confused because the linked issue seems unrelated. #227
> 
> My recommendation is to annotate the screenshot. Also provide more context on how this relates to the issue.

The image used as SVG gradient has a 1px space on the left and right - without this limitation, we could just be using colors. On browser platforms that don't support scrollbar styling this is making the right tear visible, while the left tear has always been visible, just ignored.

Ideally, we should remove the image and use the tailwind gradient colors for left and right. For what it's worth, the current PR does indeed solve the right tearing, tho it should do the left one too IMHO 😅

**Comment by shamimbinnur** [comment]
@bdougie I added the annotated screenshot.

**Comment by bdougie** [comment]
> @bdougie I added the annotated screenshot.

Wow. I wasn't event looking there or noticed. Annotations help.

**Review by bdougie — APPROVED** [review]

**Pull request merged**
