### PR TITLE
feat: organize voted repo list by week

### LINKED ISSUE #198: Display user submission and votes by Week
Image

- [x] Remove the layout toggle
- [ ] Update the API to include submissions by week

### PR DESCRIPTION
**Pull request by Deadreyo**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

In "My Votes" repo list, organizes it by weeks, specifically organizes it by This Week, Last Week & Older.

## Related Tickets & Documents

closes #198 
## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
A few things while QA-ing this. I mistakenly missed that you were organizing this filtering based on the user's votes. Seeing this live confirms that this is not needed. 

Screen Shot 2022-11-02 at 7 49 48 AM

Currently, my votes show as older since I did not vote at all this week. This will be the majority of users, which is confusing when you do not have context that recent votes will be filter differently. 

The ultimate goal is to filter the `recent` submissions into this week, last week, and older. This project is meant to show up and coming projects voted by the community.

## Please update the following. 
- [ ] remove the filtering from myvotes
- [ ] add filtering to the "recent" filter only.

As a user, I would like to see repositories recently submitted organized by week, and sorted by most voted.

**Review by bdougie — CHANGES_REQUESTED** [review]
The focus on the PR is on myVotes, but after reviewing the focus needs to be on recently submitted. https://github.com/open-sauced/hot/pull/393#issuecomment-1300211651

**Comment by Deadreyo** [comment]
> 

I will make a quick fix for this, which will assume that the "This Week" and "Last Week" lists are not long, but the issue and PR I'm working on aren't focusing on the pagination and load more, so will be better to have them separate.

Realistically we will need new issues which will have to look into how limits and pages and "Load More" works, which would be responsible for making the correct "Load More" behavior for these lists if they are too long, would also handle not hiding the whole repo list when loading more, would not display "Load More" if there isnt more, and other enhancements that can be thought of.

**Comment by bdougie** [comment]
screenshot

This calendar shows on each filter. Can you remove it?
<details><summary>Browser metadata</summary>





```
Path:      /recent
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1146 x 1336 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-393--hot-sauced-ui.netlify.app%2Frecent&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1146x1336&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-393--hot-sauced-ui.netlify.app/recent) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6364fb13952a500008d6df30&commentID=636933958306d7004ec7d034&resolution=resolved)

**Comment by Deadreyo** [comment]
> screenshot
> 
> This calendar shows on each filter. Can you remove it?
> Browser metadata
> 
> [Open Deploy Preview](https://deploy-preview-393--hot-sauced-ui.netlify.app/recent) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6364fb13952a500008d6df30&commentID=636933958306d7004ec7d034&resolution=resolved)

solved

**Comment by Deadreyo** [comment]
> @open-sauced/triage team please take a look as well.
> 
> I did notice that when viewing the page the data is not filtered right away. I need to click on another filter and then back to see the data filtered by week.
> 
> update:
> 
> link to video https://www.loom.com/share/e4849b2dc97949f0a7bbbccf8f64168d

@bdougie fixed as well

**Review by bdougie — APPROVED** [review]

**Pull request merged**
