### PR TITLE
feat: implement github login

### LINKED ISSUE #20: Need Open Sauced GitHub Login
### Type of feature

Feature

### Current behavior

The user profile is currently a placeholder. Need a GitHub login to confirm the following

- stars
- Open sauced goals account
- public comments

image

### Desired solution

We can mirror the logging from github.com/bdougie/live or github.com/open-sauced/open-sauced

1. Add login functionally to the Astro app
2. Replaces the Generic Avatar with the logged in user Avatar

### Additional context

The open sauced login is powered by a GitHub App Id 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nulfrost**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds github login, still a WIP.

**Current issue I'm facing**
For some reason after signing in it breaks everything. Changes aren't being picked up when I edit code and I'm not able to sign out. This only happens *after* signing in, before that everything works fine.

**Steps to reproduce**

1. Pull in these changes
2. Install the dependencies 
3. Start the dev server and navigate to http://localhost:3000 in the browser
4. Make a small, visual change and note that it is reflected in the browser
5. Click on the image in the top right and sign in with your github account
6. Once you're redirected back to the page, try and make another visual change, you'll notice the page isn't updated

I'm not exactly sure what's happening or why this issue only occurs after signing in but that's one of the things I'm stuck on. I've never ran into an issue like this before but I'm assuming it might be related to Astro, definitely need help on this one 😅

## Related Tickets & Documents
Resolves #20 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Possibly testing in the live environment once this is all sorted.

## [optional] What gif best describes this PR or how it makes you feel?
ahhhh

### CODE REVIEW

**Comment by bdougie** [comment]
I clone this locally and took a at the Deploy Netlify preview as well. I was able to confirm it is broken on the deploy preview due to the site being redirected to the production hot.opensauced.pizza url

**Comment by nulfrost** [comment]
> I cloned this locally and took a at the Deploy Netlify preview as well. I was able to confirm it is broken on the deploy preview due to the site being redirected to the production hot.opensauced.pizza url.
> 
> I also noticed the way the data is being fetched, it does stall out and not fetch after the redirected. When I added a console.log to the function in the src/lib/database.js it refetched the data fine.
> 
> I believe there needs to be a refetch after login so supabase can confirm the role level security based on the logged in user.
> 
> #75 will help this, but I think the useEffect in that PostWrap will need context of the user change.

ok so i've seemed to have got it working now but i think the bug related to everything breaking after logging in might be related to vite, see this issue here https://github.com/withastro/astro/issues/2004. It was said to have been fixed in a release, am I okay to upgrade astro and test? Also for the log in and log out buttons, should I do it in this PR or should that be a separate issue?

**Comment by bdougie** [comment]
> It was said to have been fixed in a release, am I okay to upgrade astro and test? Also for the log in and log out buttons, should I do it in this PR or should that be a separate issue?

For the sake of testing in the context of this feel free to upgrade Astro in your PR. If that is not it, we may look into putting a fix for #80 and cut a 2.0 release that uses React/Vite only.

**Comment by 0-vortex** [comment]
> > It was said to have been fixed in a release, am I okay to upgrade astro and test? Also for the log in and log out buttons, should I do it in this PR or should that be a separate issue?
> 
> For the sake of testing in the context of this feel free to upgrade Astro in your PR. If that is not it, we may look into putting a fix for #80 and cut a 2.0 release that uses React/Vite only.

Took the liberty of fixing any lock file issues in upstream, restoring from main should cover everything now, including latest version of astro! 🍕

**Comment by nulfrost** [comment]
> > It was said to have been fixed in a release, am I okay to upgrade astro and test? Also for the log in and log out buttons, should I do it in this PR or should that be a separate issue?
> 
> For the sake of testing in the context of this feel free to upgrade Astro in your PR. If that is not it, we may look into putting a fix for #80 and cut a 2.0 release that uses React/Vite only.
Did pull in the upgrade but no dice on the fix, still the same issue


> > > It was said to have been fixed in a release, am I okay to upgrade astro and test? Also for the log in and log out buttons, should I do it in this PR or should that be a separate issue?
> > 
> > 
> > For the sake of testing in the context of this feel free to upgrade Astro in your PR. If that is not it, we may look into putting a fix for #80 and cut a 2.0 release that uses React/Vite only.
> 
> Took the liberty of fixing any lock file issues in upstream, restoring from main should cover everything now, including latest version of astro! 🍕

Thank you! Worked like a charm

**Review by bdougie — APPROVED** [review]
@nulfrost I am going to merge what you have in because the custom hook will be useful. To further solve this problem. I think we can use cookies for basic info if Astro continues to be a challenge, but for now, supabase will be the server that maintains the state. 

I am going to create a few follow-up PRs to connect auth to voting. 

Appreciate the work you put into this.

**Pull request merged**
