### PR TITLE
feat: Made the contributors StackedAvatars component reusable

### LINKED ISSUE #287: Feature: Make the contributors StackedAvatars component reusable
### Type of feature

🍕 Feature

### Current behavior

The contributor's avatar list has been built 3 times in 3 different places. Let's make this a reusable component. 

### Suggested solution

Port this code into one reusable component

https://github.com/open-sauced/hot/blob/main/src/components/HotRepositories.tsx#L126-L132
https://github.com/open-sauced/hot/blob/main/src/components/PostList.tsx#L69-L77
https://github.com/open-sauced/hot/blob/main/src/components/Hero.tsx#L108 - not implemented yet https://github.com/open-sauced/hot/issues/265

### Additional context

related https://github.com/open-sauced/hot/issues/286

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by SunGoldTech**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR replaces duplicate codes with one reusable one.

## Related Tickets & Documents
closes #287 
[#287 ](uhttps://github.com/open-sauced/hot/issues/287#issue-1327815977)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by 0-vortex** [comment]
@SunGoldTech (meant as a huge compliment) you are too quick! 😅 🍕 

There's a pending `beta` -> `main` merge incoming, if you take a look at the [beta branch](https://github.com/open-sauced/hot/tree/beta), do you think it would be possible to rebase this PR against that branch/incoming change? 

If not, let's get this PR on main and I will take care of the merge! 🍕

**Review by bdougie — APPROVED** [review]
LGTM. Thanks for another great contribution

**Comment by SunGoldTech** [comment]
> @SunGoldTech (meant as a huge compliment) you are too quick! 😅 🍕
> 
> There's a pending `beta` -> `main` merge incoming, if you take a look at the [beta branch](https://github.com/open-sauced/hot/tree/beta), do you think it would be possible to rebase this PR against that branch/incoming change?
> 
> If not, let's get this PR on main and I will take care of the merge! 🍕

I'm still trying to get my hands dirty on git/github workflows.. But thanks for the compliment :)

**Comment by SunGoldTech** [comment]
> LGTM. Thanks for another great contribution

Pleasures are mine✌.. I'm super excited to be here😊😊

**Pull request merged**
