### PR TITLE
feat: allow :emoji: in repository list descriptions

### LINKED ISSUE #370: Bug: markdown emoji do not render in summary lists
### Describe the bug

Raw markdown being shown in project previews instead of emoji

F4D5EC48-C4A0-42A2-A83E-676F9F252321

### Steps to reproduce

1. Go to hot.opensauced.pizza
2. Scroll to ossu/computer-science or another project with markdown emoji in the title 
3. See raw markdown `:mortar_board:` instead of icon 🎓 

### Affected services

hot.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Uses [`node-emoji`](https://www.npmjs.com/package/node-emoji) to "emojify" repository descriptions. Strings like `"a :fire: :pizza: !"` get emojis converted to outputs like `" a 🔥 🍕 !"`. 

## Related Tickets & Documents

Fixes #370

## Mobile & Desktop Screenshots/Recordings

The hero search shows two examples when searching for `ossu`:

Screenshot of hero search with two repos for ossue, both with starting colon emoji names replaced by actual emojis

For older repos below, I added `olderData[0].description = ':tada: ' + olderData[0].description` in `RecentRepoListWrap.tsx`'s `useEffect`: 

Screenshot of 'Older' repository list showing the 🎉 emoji at the start of a first entry's description

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed _(there are no `.tsx` file tests yet)_
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Donkey from Shrek smiling at the camera charmingly

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
Looks great :pizza: 

Did you test it for the search results as well?
Here is what I get from the deploy preview

emojify

**Comment by 0-vortex** [comment]
Hey, thanks for opening the PR. Have a couple of questions/concerns before reviewing (big 👍)

1. @TAKANOME-DEV the effort of hooking the emoji translator into every frontend bit of code seems pointless, it would be best to implement the description translator in the client hook to have it available everywhere
2. @JoshuaKGoldberg have some maintenance concerns about `node-emoji`, but the biggest blocker is that it doesn't look like it's doing purely GFM emojis, curious what your thoughts are on using a GFM only emoji translator like [node-github-emoji](https://github.com/rhysd/node-github-emoji)

**Comment by JoshuaKGoldberg** [comment]
> best to implement the description translator in the client hook

Oh, is that something you'd like me to do in this PR?

> doesn't look like it's doing purely GFM emojis

Sorry, I'm not following - is it that you want to make sure it does nonstandard GitHub emojis such as `:shipit:` :shipit: too?

**Comment by 0-vortex** [comment]
> Oh, is that something you'd like me to do in this PR?

If you are willing to edit the description in multiple places (like the search dropdown) then it would require more effort - my suggestion was to limit that effort for this PR, somehow

> > doesn't look like it's doing purely GFM emojis
> 
> Sorry, I'm not following - is it that you want to make sure it does nonstandard GitHub emojis such as `:shipit:` :shipit: too?

Just wanted to make sure it has parity with GitHub readmes, from a first time viewers' perspective, `node-emoji` looks like it's doing more than just GFM 😅

**Comment by JoshuaKGoldberg** [comment]
> the search dropdown

D'oh! I had been looking at the wrong place 🤦 just pushed fc37ee2 to apply to the searched repo card too.

> limit that effort for this PR

Yeah, that's a good question. In theory the backend could normalize PR descriptions to have actual emojis rather than `:name:`s. But then they'd be different from the repos themselves. Not sure.

At any rate, the two codepaths that end up in this repo's `emojify(description)`s don't seem the same to me. But if you see a way to deduplicate I'd love that! 😄 

> `node-emoji`

Yeah I haven't found a library that works better. `node-emoji` seems to be in-and-out of maintenance and I never ended up pushing https://github.com/omnidan/node-emoji/pull/113 through. Definitely open to suggestions here!

**Review by bdougie — APPROVED** [review]
Let's ship what we have here and come back with [this](https://github.com/open-sauced/insights/pull/1085) is live in insights to have parity.

**Pull request merged**
