### PR TITLE
feat: load more records

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds the ability to fetch more records in lieu of infinite scroll. Infinite scroll is an expensive feature and this is the first step towards that.

## Related Tickets & Documents

#81 

## Mobile & Desktop Screenshots/Recordings

Screen Shot 2022-02-20 at 10 11 44 PM
Screen Shot 2022-02-20 at 10 11 25 PM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

> In Safari when loading more repos the page stayed in its current position but in Chrome and Edge the page scrolled to the bottom of the list. This is more so a difference in how the browsers handle new data being added to the page, but something I noticed.

### CODE REVIEW

**Review by jasonericdavis — APPROVED** [review]
LGTM. There were only 2 things that I noticed that dont affect the functionality but may be considered:

1. The limit value stays the same when switching active links. In this scenario, it is fine since there is a limit on the number of repos that can be shown. In the path to infinite scrolling, we will probably want to either cache or reset the limit value when switching links to avoid loading a large set of data.

2. In Safari when loading more repos the page stayed in its current position but in Chrome and Edge the page scrolled to the bottom of the list. This is more so a difference in how the browsers handle new data being added to the page, but something I noticed.

**Comment by bdougie** [comment]
> LGTM. There were only 2 things that I noticed that dont affect the functionality but may be considered:
> 
> 1. The limit value stays the same when switching active links. In this scenario, it is fine since there is a limit on the number of repos that can be shown. In the path to infinite scrolling, we will probably want to either cache or reset the limit value when switching links to avoid loading a large set of data.
> 2. In Safari when loading more repos the page stayed in its current position but in Chrome and Edge the page scrolled to the bottom of the list. This is more so a difference in how the browsers handle new data being added to the page, but something I noticed.

Fixed the active link thing https://github.com/open-sauced/hot/pull/127/commits/032c1bcabd6ad4ddb32f38848bcfbc4fa2a16b08

Going to open an issue for that safari thing.

**Comment by 0-vortex** [comment]
I see a couple of things:
- "load more" button appears before anything is loaded having text height
- "load more" button also has text height if it's the only element on row (items modulo 3)
- the order being changed once "load more is pressed"

There are a couple of thoughts I have on history location switching with a new page, but this can be covered by the vite pre-render part of the issue - we can do it as part of a global hydration issue or part of this :D

**Comment by bdougie** [comment]
> "load more" button appears before anything is loaded having text height

This is fixed in https://github.com/open-sauced/hot/pull/127/commits/98caca1b87accaf41becc7ab46554bfcbe913731

> "load more" button also has text height if it's the only element on row (items modulo 3)
> the order being changed once "load more" is pressed

Both of these will get issues opened after I merge this.

**Pull request merged**
