### PR TITLE
My First Open source contribution

### PR DESCRIPTION
**Pull request by helloanjalig**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
Hey @helloanjalig, can you explain what this pr is all about?

**Comment by bdougie** [comment]
Thanks for the contribution, however, this is not needed or invalid. Consider working on a [good-first-issue](https://github.com/open-sauced/open-sauced/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

**Comment by helloanjalig** [comment]
I am learning.
I will work in a proper way, Kindly allow
and That pr is about my first open source work way
I saw someone did same
that's why
I got it now, I will try my best

**Comment by bdougie** [comment]
Considering checking out the LinkFree project, they have a decent onboarding that guides beginners https://linktr.ee

**Pull request closed without merging**
