### PR TITLE
fix: make year dynamic in footer

### PR DESCRIPTION
**Pull request by tmsagarofficial**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Refers to issue #455 
This PR tries to automatically update the year of the copyright section based on the current year  

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Review by TAKANOME-DEV — APPROVED** [review]
LGTM :rocket:

**Review by bdougie — CHANGES_REQUESTED** [review]
This fixes desktop but not the mobile footer.

image

**Comment by tmsagarofficial** [comment]
> This fixes desktop but not the mobile footer.
> 
> image

Will try to make it work on mobile too

Any Guidnce to  me if u hav anything specific to this issue is really appreciated

**Comment by 0-vortex** [comment]
> > This fixes desktop but not the mobile footer.
> > 
> > image
> 
> Will try to make it work on mobile too
> 
> Any Guidnce to  me if u hav anything specific to this issue is really appreciated 

Apply same procedure on line 153 - the footer is duplicated once for desktop and once for mobile! 👍

**Comment by NsdHSO** [comment]
LGTM

**Comment by tmsagarofficial** [comment]
Any other changes required ? 😅

**Comment by tmsagarofficial** [comment]
@takanome-dev @0-vortex Pls review and let me know if there are any other changes 🚀

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍 

Was busy over the weekend, merging this in now! 🚀 🍕

**Pull request merged**
