### PR TITLE
fix: Submit button z-index is below the hot repos

### LINKED ISSUE #237: Bug: Submit button z-index does is below the hot repos.
### Describe the bug

Screen Shot 2022-07-26 at 8 39 59 PM
Screen Shot 2022-07-26 at 8 39 47 PM

The easy solution is add z-index, but I am not confident that is the best solution. 

### Steps to reproduce

When viewing the submission form and scrolling up into the Hot Repos section, the form is hidden.

1. Click login
2. Open the submit a repo form (bottom right after logging in)
3. scroll up 

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Ryankolsen**
Definitely my first pull request. I apologize if I did not use the right form, I'm trying! 

**Also, I definitely only changed line 73, please point me in the right direction if I screwed this up somehow:
I literally just added:  z-[1] 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR fixes the RepoSubmission.tsx component to be positioned above/in front of the hot repos. I changed the Z index rather than messing with a whole lot of CSS. (I thought it was best to keep my first attempt simple)

## Related Tickets & Documents

Closes #237 

## Mobile & Desktop Screenshots/Recordings

Blocked Image:
SuggRepoImgBlocked

Corrected Z Index
SuggRepoImgShownrev

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Nope, unless someone wants to use a different method other than z-index to resolve this. I also wanted to add a black border to show a bit more contrast...but I really don't want to start making unauthorized changes to a project that I'm just starting to get involved with. 

## [optional] What gif best describes this PR or how it makes you feel?

whoop-the-office

### CODE REVIEW

**Comment by 0-vortex** [comment]
Changed `z-[1]` to `z-10` to avoid having an on the fly generated CSS class, it should be good to go after this! 🍕

**Comment by Ryankolsen** [comment]
Thank you!! sorry, this was my first time using Tailwind and I appreciate all the help!

...also, should I delete this branch now?

**Comment by 0-vortex** [comment]
> Thank you!! sorry, this was my first time using Tailwind and I appreciate all the help!
> 
> 
> 
> ...also, should I delete this branch now? 

No worries, the deploy preview was broken and reading on z-index while reviewing made me realize it's a minor improvement, not really worth a review or change request - as a maintainer I could just add that along with the merge! 🍕 

You can delete the branch of course, but this is all happening inside your fork so not needed. When you sync your fork with upstream your branches will remain, if you are not bothered by them while writing code I suggest keeping them around - they act like fixed snapshots in time of the code you write, sometimes it makes sense when you are writing a blog post to, for example, link a PR or a branch you are running in the fork for people to have additional context on your post! 🍕

**Comment by Ryankolsen** [comment]
This all makes sense now - thank you again for all the help. I used a ton of Git, but it is very different when you're working with others. I'm excited to contribute in a more meaningful way, but right now I'll fix whatever I can 
:)

**Comment by 0-vortex** [comment]
> This all makes sense now - thank you again for all the help. I used a ton of Git, but it is very different when you're working with others. I'm excited to contribute in a more meaningful way, but right now I'll fix whatever I can
> :)

Thank you, every contribution is meaningful! 
Glad you are enjoying open source 🍕

**Pull request merged**
