### PR TITLE
fix: added the right repo social image.

### LINKED ISSUE #17: Feature: Replace placeholder image with repo social card
### Type of feature

Feature

### Current behavior

Prior to #13, this app was pulling in the social cards from GitHub. 

https://github.com/open-sauced/hot-sauce/blob/main/src/components/SocialImage.jsx

This is the previous fetching of the social card image. 

https://github.com/open-sauced/hot-sauce/blob/c3e28250cc27ee7b43b5134b1e883bc8c2864338/src/pages/index.astro#L14-L21

Previous PR where this was working https://github.com/open-sauced/hot-sauce/pull/1/files

### Desired solution

Add the social image in replace of the placeholder. See the previous PR where this was:
Screen Shot 2021-12-17 at 4 55 20 PM

Example pulling images from open graph.

Group 2

### Additional context

[Previous site with social card
](https://4000735cf7f--hot-sauced-ui.netlify.app)
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hokagedemehin**
## What type of PR is this? (check all applicable)

- [x] 🐛 Bug Fix

## Description

This PR replaces the previous placeholder image of each card with the corresponding repository social image that will be generated by Github. Also, I removed the actions buttons at the bottom as suggested by @bdougie and placed the upvote button at the top right corner of the card at the same line where the contributor's avatars are located. Only the PostGrid file was changed for this PR

## Related Tickets & Documents

Fixes #17 

## Added tests?

- [x] 🙅 no, because they aren't needed

## Added to documentation?

- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by hokagedemehin** [comment]
Hello @0-vortex @kelvinsekx 

Please could you help with the netlify test, it seems to be failing because of a package that is missing. This is what I found in the build logs

```js
Error: The package "esbuild-linux-64" could not be found, and is needed by esbuild.
9:52:49 AM: If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
9:52:49 AM: by esbuild to install the correct binary executable for your current platform.
```

**Comment by kelvinsekx** [comment]
@hokagedemehin you are having that error because your laptop OS is windows.

**Comment by kelvinsekx** [comment]
> Hello @0-vortex @kelvinsekx
> 
> Please could you help with the netlify test, it seems to be failing because of a package that is missing. This is what I found in the build logs
> 
> ```js
> Error: The package "esbuild-linux-64" could not be found, and is needed by esbuild.
> 9:52:49 AM: If you are installing esbuild with npm, make sure that you don't specify the
> "--no-optional" flag. The "optionalDependencies" package.json feature is used
> 9:52:49 AM: by esbuild to install the correct binary executable for your current platform.
> ```

To resolve it, install the package on your end, and don't forget to save it as a development package

`npm i -D esbuild-linux-64`.

Everything should be fine when you do this.

**Comment by hokagedemehin** [comment]
Na wa oh. This life no equal at all.

May God bless me to buy Mac one day 😩😩😩😩😩

**Comment by kelvinsekx** [comment]
Can you please have your other PR merged?

You don't necessarily need two PRs at a time.

**Comment by kelvinsekx** [comment]
> Na wa oh. This life no equal at all.
> 
> May God bless me to buy Mac one day 😩😩😩😩😩
> 
> But in that case, why did the other PR not have the same issue. All checks passed in my second PR

Did you just made a 'git pull' ?

**Comment by hokagedemehin** [comment]
I am getting this error when I tried running the code you suggested earlier

```js
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-linux-64@0.14.8: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by kelvinsekx** [comment]
> I am getting this error when I tried running the code you suggested earlier
> 
> ```js
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for esbuild-linux-64@0.14.8: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
> npm ERR! notsup Valid OS:    linux
> npm ERR! notsup Valid Arch:  x64
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64
> ```

`esbuild-windows-64": "^0.14.5"`

Install that instead. Pardon me, I literally just woke up.

**Comment by hokagedemehin** [comment]
> Can you please have your other PR merged?
> 
> You don't necessarily need two PRs at a time.

Maybe you can merge the #48 pull request that has passed all the necessary tests and is fine. I will resolve all the conflicts with this one and do it again if necessary

**Comment by kelvinsekx** [comment]
> > Can you please have your other PR merged?
> > You don't necessarily need two PRs at a time.
> 
> Maybe you can merge the #48 pull request that has passed all the necessary tests and is fine. I will resolve all the conflicts with this one and do it again if necessary

You took this on first. 
You are supposed to be done with this before taking another on. If you have any problem, put it here and we can discuss about it.

**Comment by hokagedemehin** [comment]
@kelvinsekx 

I installed `npm i -D esbuild-windows-64` and still failing the Netlify test and some development test

At this point, I don't know what might be wrong again

**Comment by 0-vortex** [comment]
> > Hello @0-vortex @kelvinsekx
> > Please could you help with the netlify test, it seems to be failing because of a package that is missing. This is what I found in the build logs
> > ```js
> > Error: The package "esbuild-linux-64" could not be found, and is needed by esbuild.
> > 9:52:49 AM: If you are installing esbuild with npm, make sure that you don't specify the
> > "--no-optional" flag. The "optionalDependencies" package.json feature is used
> > 9:52:49 AM: by esbuild to install the correct binary executable for your current platform.
> > ```
> 
> To resolve it, install the package on your end, and don't forget to save it as a development package
> 
> `npm i -D esbuild-linux-64`.
> 
> Everything should be fine when you do this.

That's not the appropriate fix for this. When switching branches he did not clean install branches, when switching to an older one some of his local dependencies were skipped and coming back to this PR required another clean install. Since `esbuild` is already part of our dependencies you should have suggested a new clean branch and running `npm ci` and check that result 🍕

**Comment by 0-vortex** [comment]
@hokagedemehin the correct fix to unblock this PR is:

```
git restore package.json npm-shrinkwrap.json -s main
```

As for your local machine, are you keeping your branches in sync with `upstream/main` and running `npm ci` consistently?

**Comment by 0-vortex** [comment]
> @hokagedemehin the correct fix to unblock this PR is:
> 
> ```
> git restore package.json npm-shrinkwrap.json -s main
> ```
> 
> As for your local machine, are you keeping your branches in sync with `upstream/main` and running `npm ci` consistently?

If your fork is behind and you are using `gh` command line:

```shell
git restore package.json npm-shrinkwrap.json -s upstream/main
```

**Comment by hokagedemehin** [comment]
First of all, thank you all for your time and input in resolving my test issues, you guys are the best

Currently, I am creating a new branch and running `git restore package.json npm-shrinkwrap.json -s main` then `npm ci` again on the new branch

After that I will make the necessary changes to reflect the changes I want to push and try to make a new PR

Hopefully, this should not have any problem. But I have learnt something new today, always run `npm ci` for every new branch you create

**Comment by 0-vortex** [comment]
> First of all, thank you all for your time and input in resolving my test issues, you guys are the best

Always glad to help

> Currently, I am creating a new branch and running `git restore package.json npm-shrinkwrap.json -s main` then `npm ci` again on the new branch
> 
> After that I will make the necessary changes to reflect the changes I want to push and try to make a new PR
> 
> Hopefully, this should not have any problem. But I have learnt something new today, always run `npm ci` for every new branch you create

That's not required, running the restore command applies those changes in the current branch, essentially this pull request; all you have to do is commit those changes to fix the CI builds, the `npm ci` command is to make sure you get your local environment up to date with main. 

When switching branches, the `npm ci` command is required only if `package.json` file is different.

Please commit the changes to this pull request. Thank you for your patience and contribution! 🍕

**Comment by hokagedemehin** [comment]
🕺🏾🕺🏾🕺🏾🕺🏾🕺🏾🕺🏾💃🏾💃🏾💃🏾💃🏾💃🏾💃🏾💃🏾💃🏾

All tests passed.  🎉🎉🎉🎉🎉🎉🎉

**Review by 0-vortex — APPROVED** [review]
dependency changes are good to go, not sure about HTML comments

**Comment by hokagedemehin** [comment]
> dependency changes are good to go, not sure about HTML comments

I could remove the codes I commented out if you are ok with the final look of each card and the placement of the upvote button

Just give me the go ahead

**Comment by bdougie** [comment]
I am still not feeling like the context of the data is needed with the social card now rendering. Can we do the following. 

1. For the image `object-fit: contain`
2. Switch the grid to 3 columns from 4
3. Remove the h1 title and description (postgrid only)

image

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 96.0.4664.110 on Mac OS 10.15.7
Viewport:  1146 x 977 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-49--hot-sauced-ui.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=96.0&resolution=1146x977&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-49--hot-sauced-ui.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61cb9495eb4eb60007be735a&commentID=61cdcd2b74273bc6919a817a&resolution=resolved)

**Comment by mtfoley** [comment]
I deleted a bunch of compliance comments.

**Comment by hokagedemehin** [comment]
> 

Hi @bdougie compliments of the season, just getting home from my second job,

I will work on your request and resolve all the merge conflicts that exist in the PR 

Thank you for your review

**Comment by hokagedemehin** [comment]
Hello @bdougie

Could you take a look at the current changes that I just committed to see if it reflects what you asked for

Thank you

**Review by bdougie — APPROVED** [review]
Thanks for taking the time and working through this contribution. There were a few curveballs that you persevered through. 

This won't be the final UI but it is works. Open to suggestions if you have them.

**Pull request merged**
