### PR TITLE
test: fix jest configuration

### LINKED ISSUE #26: Feature: Make Jest work with this project.
### Type of feature

Test

### Current behavior

There is now one test included in this project. It will not run using Vite. From my research, this is possible with the inclusion of Babel. 

https://github.com/open-sauced/hot/pull/25

### Desired solution

Make `npm t` work

https://github.com/open-sauced/hot/blob/main/src/lib/humanizeNumber.test.js

### Additional context

https://vitest.dev/ is another solution, but currently in alpha

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0-vortex**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds a working test configuration. 
It's mostly based on https://jestjs.io/docs/tutorial-react which implies create-react-app compatibility

## Related Tickets & Documents

closes #26 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

- add unit tests to make coverage work
- add react unit tests to check if they work

### CODE REVIEW

**Comment by 0-vortex** [comment]
Implemented eslint for the additional packages we got, put some defaults onto them but we could start to architect and `@open-sauced/eslint` config package to work across the board

**Review by bdougie — APPROVED** [review]
LGTM

**Comment by bdougie** [comment]
> Implemented eslint for the additional packages we got, put some defaults onto them but we could start to architect and `@open-sauced/eslint` config package to work across the board

An overall eslint config for open-sauced sounds ideal. Based on the response with this project, there will probably be more small one-off repos that will need to get up and running quickly.

**Review by bdougie — COMMENTED** [review]
Looking into this further. The one test written fails on an ESM import. 

```
    Details:

    /workspaces/hot/src/lib/humanizeNumber.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import humanizeNumber from './humanizeNumber';
```

**Comment by 0-vortex** [comment]
can you throw me a gist with some code to test?

**Comment by 0-vortex** [comment]
> Looking into this further. The one test written fails on an ESM import.
> 
> ```
>     Details:
> 
>     /workspaces/hot/src/lib/humanizeNumber.test.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import humanizeNumber from './humanizeNumber';
> ```

try ```npm ci && npm t -- --no-cache```
also, what is workspaces? 🍕

**Comment by bdougie** [comment]
Workspaces is Codespaces environments

**Comment by 0-vortex** [comment]
> Workspaces is Codespaces environments

Is that pressing dot or local environment? Not sure how to use the terminal in codespaces

**Comment by bdougie** [comment]
This is not using dot, but using a full codespaces environment to test. Same result with the `npm ci && npm t --no-cache`
Screen Shot 2021-12-22 at 9 00 03 AM

But, I tested locally and it's fine. I think Codespaces is doing something weird with the environment. No need to debug that here on this PR.

**Comment by 0-vortex** [comment]
> This is not using dot, but using a full codespaces environment to test. Same result with the `npm ci && npm t --no-cache` Screen Shot 2021-12-22 at 12 04 07 PM
> 
> But, I tested locally and it's fine. I think Codespaces is doing something weird with the environment. No need to debug that here on this PR.

tested in my codespaces and some runners come with poisoned cache, doing `npm cache clean --force` seems to do the trick if you run it at least one time 🍕

**Pull request merged**
