### PR TITLE
fix: content related to take action update

### PR DESCRIPTION
**Pull request by blackgirlbytes**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

I created an earlier PR for the [Take Action](https://github.com/bdougie/take-action/pull/8). A comment will be created if the issue is already assigned to a previous contributor. This PR contains the messaging of the comment. The comment will say: "Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor. Please communicate with the assigned contributor to confirm the status of the issue."

Please let me know if you want to change the wording of the comment. 

## Related Tickets & Documents
No issue is opened for this, but this is related to this [issue ](https://github.com/bdougie/take-action/issues/7) and this [PR](https://github.com/bdougie/take-action/pull/8).

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — CHANGES_REQUESTED** [review]
restore npm-shrinkwrap.json from main branch please :D

**Comment by 0-vortex** [comment]
> restore npm-shrinkwrap.json from main branch please :D

If you are using `gh` command line:

`git restore npm-shrinkwrap.json -s upstream/main`

If you are using git clone, update your fork and do:

`git restore npm-shrinkwrap.json -s origin/main`

**Comment by blackgirlbytes** [comment]
I added it back @0-vortex ! Thanks for noticing. I didn't realize I deleted that file.

**Comment by 0-vortex** [comment]
> I added it back @0-vortex ! Thanks for noticing. I didn't realize I deleted that file.

Wasn't you, we had some PRs with dependencies mismatches, and now `prop-types` is in `npm-shrinkwrap.json` but not `package.json` - tho another PR is fixing that and I did not want to scope creep here :D

I'll pass this ASAP, thank you!

**Review by 0-vortex — APPROVED** [review]

**Pull request merged**
