### PR TITLE
feat: added custom tailwind variables and removed anti patterns

### LINKED ISSUE #315: Remove tailwinds anti-pattern in Hero.tsx
Context is on the tracking issue - https://github.com/open-sauced/hot/issues/267

This issue only needs changes to this file.

### PR DESCRIPTION
**Pull request by AlexVCS**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ✅] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

I added a few custom Tailwind variables and removed more of the anti patterns in Hero.tsx.

This PR is a work in progress fix for #315 

## Related Tickets & Documents

Fixes #315 

## Mobile & Desktop Screenshots/Recordings

Screen Shot 2022-09-10 at 7 36 22 PM

## Added tests?

- [ ] 👍 yes
- [✅ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [✅ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

kob

### CODE REVIEW

**Comment by 0-vortex** [comment]
Hey @AlexVCS thanks for opening the PR, however this is moving the hardcoding from pixels to pixel css classes - simply put, none of the components were initially implemented as mobile first, which brings us to a responsive predicament when tailwind is a mobile first framework; as such, the baseline tailwind classes are defined in responsive units.

As per the above limitations, tailwind classes should be applied when possible, when not possible there are multiple things to try:
- aproximating to the closest available tailwind class
- investigating fixing the component
- keep the hardcoding but switch from pixels to responsive units

Adding additional tailwind classes based on faulty implementations is not in the above list because it leads to more terrible complications. I would not close the PR as some of the work is compatible with the requirement, however the custom sizing needs to be undone 😅

**Comment by AlexVCS** [comment]
> Hey @AlexVCS thanks for opening the PR, however this is moving the hardcoding from pixels to pixel css classes - simply put, none of the components were initially implemented as mobile first, which brings us to a responsive predicament when tailwind is a mobile first framework; as such, the baseline tailwind classes are defined in responsive units.
> 
> As per the above limitations, tailwind classes should be applied when possible, when not possible there are multiple things to try:
> 
> * aproximating to the closest available tailwind class
> * investigating fixing the component
> * keep the hardcoding but switch from pixels to responsive units
> 
> Adding additional tailwind classes based on faulty implementations is not in the above list because it leads to more terrible complications. I would not close the PR as some of the work is compatible with the requirement, however the custom sizing needs to be undone 😅

Thanks for letting me know! I tried it as I saw #267 talked about potentially creating variables. My apologies, I will remove them and take your advice on how to proceed!

**Comment by AlexVCS** [comment]
Would the shadow on line 61 be considered an anti pattern?

`<div className="mt-11 px-4 gap-x-2.5 py-2.5 justify-between bg-white shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] rounded-2xl md:min-w-[26.375rem] flex">`

Thanks!

**Comment by 0-vortex** [comment]
> Would the shadow on line 61 be considered an anti pattern?
> 
> `<div className="mt-11 px-4 gap-x-2.5 py-2.5 justify-between bg-white shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] rounded-2xl md:min-w-[26.375rem] flex">`
> 
> Thanks!

Technically yes, however in this particular case, https://tailwindcss.com/docs/box-shadow only `shadow-2xl` would be a viable replacement and I am not sure if that is visually satisfying, however I would personally go with `shadow-2xl` or lower one to keep consistency! 🍕

**Comment by AlexVCS** [comment]
> > Would the shadow on line 61 be considered an anti pattern?
> > `<div className="mt-11 px-4 gap-x-2.5 py-2.5 justify-between bg-white shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] rounded-2xl md:min-w-[26.375rem] flex">`
> > Thanks!
> 
> Technically yes, however in this particular case, https://tailwindcss.com/docs/box-shadow only `shadow-2xl` would be a viable replacement and I am not sure if that is visually satisfying, however I would personally go with `shadow-2xl` or lower one to keep consistency! 🍕

Thank you! I went with that and it looks pretty good:

Screen Shot 2022-09-13 at 3 15 58 PM

**Comment by 0-vortex** [comment]
> > > Would the shadow on line 61 be considered an anti pattern?
> > > `<div className="mt-11 px-4 gap-x-2.5 py-2.5 justify-between bg-white shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] rounded-2xl md:min-w-[26.375rem] flex">`
> > > Thanks!
> > 
> > 
> > Technically yes, however in this particular case, https://tailwindcss.com/docs/box-shadow only `shadow-2xl` would be a viable replacement and I am not sure if that is visually satisfying, however I would personally go with `shadow-2xl` or lower one to keep consistency! 🍕
> 
> Thank you! I went with that and it looks pretty good:
> 
> Screen Shot 2022-09-13 at 3 15 58 PM

Looks good to me! 👍

**Comment by bdougie** [comment]
@AlexVCS let us know when this is ready to review.

**Comment by AlexVCS** [comment]
This is ready for review, my sincere apologies for the delay!

**Pull request merged**
