### PR TITLE
v2.26.0-alpha.6 -> beta

### PR DESCRIPTION
**Pull request by 0-vortex**
this is fixing https://github.com/open-sauced/hot/pull/375/files#diff-8106b33209645813f4d86b44dd0135c305184ab013153e6196303b8bc07e86bb

hopefully 😅 🍕

### CODE REVIEW

**Comment by bdougie** [comment]
It might make sense to nuke this alpha branch and start is all over. The biggest loss is #322, but I already opened an issue for that to be re-done on beta #380

**Comment by 0-vortex** [comment]
> It might make sense to nuke this alpha branch and start is all over. The biggest loss is #322, but I already opened an issue for that to be re-done on beta #380

https://github.com/open-sauced/hot/tree/alpha-fix just a little bit longer :D

**Comment by 0-vortex** [comment]
@bdougie seems like a side effect of all the magic I've done erased the grid components, should those be added back in?

**Comment by bdougie** [comment]
> @bdougie seems like a side effect of all the magic I've done erased the grid components, should those be added back in?

No that has been dead code for awhile. It is fine to be deleted.

**Pull request merged**
