### PR TITLE
fixed the issue on avatar overlay

### LINKED ISSUE #279: Bug: Left-most avatar get overlapped during hover
### Describe the bug

image

### Steps to reproduce

1. Go to [https://hot.opensauced.pizza/](https://hot.opensauced.pizza/)
2. Hover to avatar in repository card

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by favourite1975**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [x] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
fix: issue on avatar overlay

## Related Tickets & Documents

Fixes #279 
## Mobile & Desktop Screenshots/Recordings

Screenshot from 2022-08-03 04-19-20

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@favourite1975 please describe what you changed and your approach. It makes it easier for folks to review this. 

cc @open-sauced/triage

**Comment by favourite1975** [comment]
@bdougie thank you for the review
I will close the pull request now and create a new one to fix that

**Comment by favourite1975** [comment]
sorry for the mistake of opening and reclosing the pull request

**Comment by shamimbinnur** [comment]
@favourite1975  You should be able to fix the errors of the existing PR by editing this!

**Comment by bdougie** [comment]
Yeah echoing what was said. No need to close and re open, just some small fixes. Everything is documented.

There is also a video https://youtu.be/Xl_Ros8XlJU

**Pull request closed without merging**
