### PR TITLE
feat: Add posthog to hot sauced project.

### PR DESCRIPTION
**Pull request by chadstewart**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR [adds] the [feature] using PostHog. 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by chadstewart** [comment]
So I just noticed that @bdougie mentioned that seeing posthog on hot sauced would be good. Dunno where to put the capture functions cause I don't know this project well but I figured I'd at least put up the code I wrote.

**Comment by 0-vortex** [comment]
> Also, this doesn't have an issue cause I did this on a whim. Should I go make an issue for this?

Nah, it's all good. That `<any>` type will probably break the build on main branch, would be the only change required. 💯 🍕

**Comment by chadstewart** [comment]
> > Also, this doesn't have an issue cause I did this on a whim. Should I go make an issue for this?
> 
> Nah, it's all good. That `<any>` type will probably break the build on main branch, would be the only change required. 100 pizza

Yeah, honestly I was thinking about making it a primitive and then I was like, "Maybe they wanted to pass something complex." I'll just make it a primitive for now.

**Review by 0-vortex — APPROVED** [review]
LGTM

**Review by bdougie — APPROVED** [review]

**Review by bdougie — APPROVED** [review]

**Pull request merged**
