### PR TITLE
feat: auth/session API call temporary at Navbar component.

### LINKED ISSUE #366: Bug: Users need to be added to database when they primarily sign up on Opensauced Pizza or hot.opensauced.pizza
### Describe the bug

##Issue
1. Users are not being added to the user table in Supabase
2. User, janie-lee-developer is not in the table in Supabase (See below image). 
3. We need to triage why.

s - you are trying to add the submit service
c - your user can't submit or vote
q - how can you triage what is broken and causing your user to not be added to the table
a - there is probably something broken in the user creation service.

### Steps to reproduce

1. Go to https://opensauced.pizza/ or https://app.opensauced.pizza/ to sign up yourself as a user, primarily. (First time login)
2. Refer this https://github.com/open-sauced/api.opensauced.pizza/issues/48#issuecomment-1269223747 to get a bearer Token.
3. Paste the bearer token to test Submit Service PUT /v1/repos/{id}/submit at Swagger https://api.opensauced.pizza/#/ .
4. Gets 401 Unauthorized response to the Submit Service PUT request.

### Affected services

opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by janie-lee-developer**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Calling Auth/session API call @ Navbar component.

## Related Tickets & Documents
 
#373 

fixes #366

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@janie-lee-developer need to update the title of the PR. 

```
feat: auth/session API call temporary at Navbar component.
```

Also, can you confirm that you are able to submit a repo? That was the original goal, to enable you to submit via the API.

**Comment by janie-lee-developer** [comment]
Hi Brian,
Pls see attached. I took my token from the console to login my bearer token to swagger.
Tried both exactly the same as your screenshot (open-sauced) and also freeCodeCamp.
Not working...
Screen Shot 2022-10-19 at 6 51 42 PM

Screen Shot 2022-10-19 at 6 50 25 PM

Screen Shot 2022-10-19 at 6 54 44 PM
Screen Shot 2022-10-19 at 6 50 20 PM
Screen Shot 2022-10-19 at 6 50 45 PM

**Comment by bdougie** [comment]
@janie-lee-developer let's do a quick screen share in the morning to confirm. Ping me on Discord when you are online.

**Review by bdougie — APPROVED** [review]
Had a call with @janie-lee-developer and discovered that this works. Just needed to log out and log in.

**Pull request merged**
