### PR TITLE
docs(readme): fix typo and unformatted link

### PR DESCRIPTION
**Pull request by Balastrong**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Fixed a typo and a broken link on README.md

(prettier also fixed some whitespaces/empty lines, I'd keep the change)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Before
image

After
image

### CODE REVIEW

**Review by TAKANOME-DEV — COMMENTED** [review]
Nice catch @Balastrong :clap: 

Nit: I'd recommend checking the [contributing file](https://github.com/open-sauced/.github/blob/main/CONTRIBUTING.md) before opening a pr (next time maybe :sweat_smile:) to make the review process smooth

Looks great otherwise 🙂

**Comment by Balastrong** [comment]
Hey @TAKANOME-DEV, thanks for the review!

I read the [contribution guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/) before creating the PR, did I miss something in particular?

The thing that comes to my mind is that I didn't create an issue, but the page says both _preferred_ and required:

> We actively welcome your pull requests, however linking your work to an existing issue is preferred.

and

> Unsolicited code is welcomed, but an issue is required for an announcement your intentions. PR's without a linked issue will be marked invalid and closed.

I didn't create one because it was only a typo and I thought it was ok. Sorry if this was required!

**Comment by TAKANOME-DEV** [comment]
> The thing that comes to my mind is that I didn't create an issue, but the page says both _preferred_ and required:
> 
> > We actively welcome your pull requests, however linking your work to an existing issue is preferred.
> 
> and
> 
> > Unsolicited code is welcomed, but an issue is required for an announcement your intentions. PR's without a linked issue will be marked invalid and closed.
> 
Yeah, you're :100: right. Thanks for taking the time to read the guidelines. 

Having the preferred and required may be a little bit confusing.
Maybe an issue can be created around that 🙂

**Review by 0-vortex — APPROVED** [review]
Great first contribution, we can live without the open issue since it's a docs improvement! 👍 

Thank you very much

**Review by bdougie — APPROVED** [review]

**Comment by bdougie** [comment]
@Balastrong would be able to create a highlight about your work on this fix?

https://opensauced.pizza/blog/social-coding-is-back

**Comment by Balastrong** [comment]
Here it is! :D

https://insights.opensauced.pizza/user/Balastrong

**Pull request merged**
