### PR TITLE
feat: Added white border to Stacked Avatars Component

### PR DESCRIPTION
**Pull request by yhoungdev**

### CODE REVIEW

**Comment by yhoungdev** [comment]
Added white borders to stacked avatars 


Group 237689

**Comment by bdougie** [comment]
@yhoungdev, would you mind adding the PR template to the description? https://github.com/open-sauced/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by yhoungdev** [comment]
Yea sure but how do i add that sir

**Comment by yhoungdev** [comment]
> do you see the edit button? Under ellipse menu.
> 
> Screen Shot 2022-09-05 at 9 24 57 AM

yea I have reopened the issue

**Comment by NsdHSO** [comment]
The target branch not be beta ?

**Comment by yhoungdev** [comment]
> The target branch not be beta ?

i have raised a PR on Beta this is a reference to it 
#328

**Pull request closed without merging**
