### PR TITLE
feat: add million.js

### LINKED ISSUE #486: Feature: Integrate million.js
### Type of feature

🍕 Feature

### Current behavior

Continued conversation from https://github.com/open-sauced/app/pull/1608 for @ayusham001

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by ayusham001**
Revolves https://github.com/aidenybai/million/issues/554
/claim https://github.com/aidenybai/million/issues/554

Closes #486

### CODE REVIEW

**Comment by ayusham001** [comment]
Hi @brandonroberts Please review my PR

**Comment by bdougie** [comment]
Really weird that lighthouse doesn't even run in production, but happy see the benfits of this PR. 

Screen Shot 2023-09-06 at 7 38 43 AM

**Review by bdougie — APPROVED** [review]

**Comment by a0m0rajab** [comment]
This is a lighthouse image from the main website: 
image

**Review by a0m0rajab — APPROVED** [review]
I am not sure about the business decision side, but this seems to have a great impact and easy adoption based on the docs they have.

**Comment by bdougie** [comment]
> I am not sure about the business decision side, but this seems to have a great impact and easy adoption based on the docs they have.

going to merge it. This project is a good place to test it out and doesn't effect any business decisions. Overall I'd love to see if we can revive this project.

**Comment by a0m0rajab** [comment]
By revive do you mean as users or as contributors?

**Comment by ayusham001** [comment]
Thank you. @bdougie

**Pull request merged**
