### PR TITLE
feat: repo submit button

### LINKED ISSUE #352: Connect the Submit a Repository button to the API (POST)
## What is needed?
The submit button in the dropdown sends a link to the discord when submitted. We need also to connect it to the submit service in the API. This will require a new [hook](https://github.com/open-sauced/hot/tree/alpha/src/hooks) (API hooks only exist on the alpha branch at the moment) called **useRepoSubmit**.

Screen Shot 2022-10-03 at 11 00 16 PM

## Things to consider
Submit the repo using the id - https://api.opensauced.pizza/#/Submit%20service/submitOneById

Screen Shot 2022-10-03 at 10 59 47 PM

### PR DESCRIPTION
**Pull request by janie-lee-developer**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

repo submission handler function is added, and tried adding existing repos like freeCodeCamp or opensauced hot repo, but it's getting me back 500 or 404 response.

1. Sign in.
2. Click User Emoticon at top right corner, and click submit repo.
3. Type in repo URL (I tried putting freeCodeCamp's repo & OpenSauced/hot repo)
4. API call returns an error with 500 or 404 response. 

## Related Tickets & Documents

Resolves #352 

## Mobile & Desktop Screenshots/Recordings

Screen Shot 2022-11-03 at 2 26 36 PM
Screen Shot 2022-11-03 at 2 26 57 PM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by mtfoley** [comment]
Hi @janie-lee-developer I'm going to make a couple of minor edits to this PR title/description so it goes smoothly out of draft later.

**Comment by bdougie** [comment]
> repo submission handler function is added, and tried adding existing repos like freeCodeCamp or opensauced hot repo, but it's getting me back 500 or 404 response.

Looking at your description. Can you provide more details on this or [Loom recording](https://www.loom.com/)? I believe we had a chat on this, but trying to catch up on the context.

**Comment by mtfoley** [comment]
I tested the deploy preview as follows:
1. Signed in as GitHub user "mtfoley"
2. clicked avatar in upper right, chose "submit a repo" option
3. typed in "https://github.com/httpie/httpie" for text field
4. Clicked submit
5. No visual feedback (e.g. toast message or otherwise), but I checked on Fetch XHR:
Request:
PUT https://beta.api.opensauced.pizza/v1/repos/httpie/httpie/submit
Response Body:
```json
{
"repo_id":"3544424",
"user_id":"3792749",
"deleted_at":null,
"id":"5",
"is_accepted":false,
"created_at":"2022-11-03T17:31:14.321Z",
"updated_at":"2022-11-03T17:31:14.321Z"
}
```
I will also note that submitting with the text field filled with "httpie/httpie", it seemed to make an attempt to submit and came back with an error message of an invalid repo.

**Comment by janie-lee-developer** [comment]
As per our conversation with Ted, submitting a new repository is not workable at this moment, because we would need to implement a way to have an access to millions of repos out there in Github. Only repos that are already in the supabase db from last version of the app can be accessible.

**Comment by bdougie** [comment]
Going to take this one over. We do not need to index millions of repos, but instead, we will queue repos for indexing here. https://github.com/open-sauced/open-sauced-goals

**Comment by bdougie** [comment]
Closing in favor of #408

**Pull request closed without merging**
