### PR TITLE
ci: check added to ensure added/modified files have tests

### PR DESCRIPTION
**Pull request by mrded**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [x] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
In order to improve test coverage, we need to ensure that proposed changes have test.

This check is very basic, it only checks that if `foo.ts` file is added/modified - `foo.test.ts` is also expected.
That should encourage developers to submit changes along with tests.

## How to use:

```
./scripts/tests-existence-checker.sh || echo 'Commited files are missing tests'
```

## TODO:
- [ ] Check `ts` and `tsx` files only.
- [ ] Better feedback: Show missing files.
- [ ] Connect script to a CI
- [ ] Remove dummy commits from the PR

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by 0-vortex** [comment]
Hey @mrded awesome to see you around! We generally like to discuss PR work in issues or discussions, we don't get many proposals so we dot'n have a real way to record them other than opening a feature issue or discussion but since this is your first PR I will just go with the flow :D

Make sure to check out the docs over at https://docs.opensauced.pizza/contributing/introduction-to-contributing/ they are not very up to date but worth a quick read to avoid issues! 🍕 

This is actually a very good idea, however I would use this as an action rather than a script. If ran as an action, we could give it a `path` to check files for, like in our case `src/` and an array of file extensions to check for like `extensions` and a third parameter like `coveragePath` linking to a JSON coverage reporter, vittest follows the same reporters as jest so we can generate that in the build step of the workflows with `npm run test:coverage` (just have to add json to it). From there on it could do a bunch of things like comment on PR, similar to our compliance action.

You don't need to write a new repo/action for that, can just go into https://github.com/open-sauced/hot/blob/beta/.github/workflows/development.yml and do the git diffing there with manual pathing like the current bash script does. Our development workflows reference https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/development.yml which are very lax, feel free to use them as a starting point or just comment out for better workflows.

GitHub actions context has the `GH_TOKEN` secret present so it can do API requests manually or through wrappers, a good convention for anticipating potential needs is to use the `.github/actions/` folder to store the equivalent of the PR `scripts` folder. Generally speaking, unless the action is calling `curl` for the API, people use the `octokit` implementation to interact with GitHub API from actions due to the environment integrations: https://github.com/octokit/action.js - they also happen to share this notation 🍕 

Hope this helps!

Also, @bdougie check this out! 👀

**Comment by bdougie** [comment]
I love this idea. I think TED covered a lot of what I was going to mention. I also agree we should discuss the approach in an issue. This would be complimentary to some of our existing action workflows.

**Comment by 0-vortex** [comment]
I also forgot to mention we are squashing PRs, so you don't have to worry about those, we just use `npm run push` for practice but enforce only conventional PRs (because we squash them).

Our conventional commit package and lint configuration could use some love but I never got around to any of that this year 😅

**Comment by mrded** [comment]
Wow, you're quick! :) Thanks for the feedback, and I'm glad to see you @0-vortex too!

I'm off next week, I'll return to this as soon as I'm back.

**Comment by mrded** [comment]
Cool, all make sense. I've created an issue (feature request) here https://github.com/open-sauced/hot/issues/323

Let me play a bit with GitHub Actions, perhaps I can make one soon.

**Pull request closed without merging**
