### PR TITLE
feat: PWA Feature added

### PR DESCRIPTION
**Pull request by yhoungdev**
Added Service worker to the application 
#### Works offline 
Screenshot from 2022-01-18 21-44-09

### CODE REVIEW

**Comment by yhoungdev** [comment]
Fixed workbox.config.js 
Screenshot from 2022-01-18 23-40-16

**Comment by mtfoley** [comment]
Hi @yhoungdev thanks for working on the project! Before putting further work into this PR, can you also create an issue to discuss what you are hoping to accomplish here and what options you had considered (and then link this PR to that issue)?

**Review by bdougie — COMMENTED** [review]
Hey, thanks for the contribution @yhoungdev but this is indeed premature. A lot of this feels copied from the docs and not specific to this project.

For example, we are still using Astro, which does not have a paved into PWA. If you would like to start a discussion and provide solutions to your issues #95 that would be appreciated.

**Comment by bdougie** [comment]
The build will not pass on Netlify while we have the index.astro file. The PWA does not what to cache.
Screen Shot 2022-01-19 at 2 43 57 PM

**Pull request closed without merging**
